name: 'gaffer-uploader'
description: 'Upload test runs and reports to Gaffer'
author: 'gaffer.sh'

branding:
  icon: 'monitor'
  color: 'blue'

inputs:
  gaffer_api_key:
    description: 'Gaffer API key for your project.'
    required: true
  report_path:
    description: 'Path to the relevant report file or directory to upload.'
    required: false
  commit_sha:
    description: 'Git commit SHA to associate with the test run report.'
    required: false
  branch:
    description: 'Git branch to associate with the test run report.'
    required: false
  test_framework:
    description: 'Test framework to associate with the test run report.'
    required: false
  test_suite:
    description:
      'Optional name of the test suite to associate with the test run report.'
    required: false

runs:
  using: node20
  main: dist/index.js
