name: 'Gaffer Upload'
description: 'Uploads Test Reports to Gaffer.sh'
author: 'Gaffer'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'green'

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Time in milliseconds'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
